"""'3'

Revision ID: 11259a7c2a91
Revises: 9f3b778df577
Create Date: 2023-01-29 00:39:39.181264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11259a7c2a91'
down_revision = '9f3b778df577'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.add_column('Perevals', sa.Column('user', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'Perevals', ['id'])
    op.create_foreign_key(None, 'Perevals', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Perevals', type_='foreignkey')
    op.drop_constraint(None, 'Perevals', type_='unique')
    op.drop_column('Perevals', 'user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
