"""'second'

Revision ID: 9f3b778df577
Revises: 
Create Date: 2023-01-29 00:20:39.631789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3b778df577'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Perevals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beauty_title', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('other_title', sa.String(), nullable=True),
    sa.Column('connect', sa.String(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beauty_title'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Perevals')
    # ### end Alembic commands ###
